output "gitlab_url" {
  description = "GitLab web UI (log in as root). HTTPS via Let's Encrypt when a domain is set."
  value       = "${local.gitlab_scheme}://${local.gitlab_host}"
}

output "registry_url" {
  description = "Container registry endpoint (HTTP — see README for the dind insecure-registry flag)."
  value       = "${local.gitlab_host}:5050"
}

output "registry_host" {
  description = "Value for the --insecure-registry flag in the demo pipeline's dind service."
  value       = "${local.gitlab_host}:5050"
}

output "gitlab_root_password" {
  description = "Initial root password."
  value       = random_password.gitlab_root.result
  sensitive   = true
}

output "git_ssh" {
  description = "Git-over-SSH endpoint (port 2222)."
  value       = "ssh://git@${local.gitlab_host}:2222"
}

output "keycloak_redirect_uri" {
  description = "Redirect URI to register on the Keycloak client for this GitLab."
  value       = "${local.gitlab_scheme}://${local.gitlab_host}/users/auth/openid_connect/callback"
}

output "dns_record" {
  description = "DNS state: what Terraform manages, or the records you need to create."
  value = (
    var.domain == "" ? "none needed — using sslip.io (${local.gitlab_host}${var.gitea_enabled ? ", ${local.gitea_host}" : ""})" :
    var.route53_zone_id != "" ? "managed by Terraform in Route 53: ${local.gitlab_host}${var.gitea_enabled ? " + ${local.gitea_host}" : ""} A ${aws_eip.cp.public_ip}" :
    "create at your DNS host (TTL 300): ${local.gitlab_host}  A  ${aws_eip.cp.public_ip}${var.gitea_enabled ? " | ${local.gitea_host}  A  ${aws_eip.cp.public_ip}" : ""}"
  )
}

output "gitea_url" {
  description = "Gitea web UI + container registry (log in as gitea_admin)."
  value       = var.gitea_enabled ? "http://${local.gitea_host}:3000" : "disabled"
}

output "gitea_admin_password" {
  description = "Gitea admin password (user: gitea_admin)."
  value       = random_password.gitea_admin.result
  sensitive   = true
}

output "cp_public_ip" {
  description = "Control-plane Elastic IP (stable across stop/start)."
  value       = aws_eip.cp.public_ip
}

output "worker_public_ips" {
  description = "Worker public IPs (change on stop/start; nothing external points at them)."
  value       = aws_instance.worker[*].public_ip
}

output "ssh_control_plane" {
  description = "SSH to the control plane."
  value       = "ssh -i ${var.project}-key.pem admin@${aws_eip.cp.public_ip}"
}

output "kubeconfig_command" {
  description = "Fetch a working kubeconfig to your machine."
  value       = "ssh -i ${var.project}-key.pem admin@${aws_eip.cp.public_ip} 'sudo cat /etc/rancher/k3s/k3s.yaml' | sed 's/127.0.0.1/${aws_eip.cp.public_ip}/' > kubeconfig && export KUBECONFIG=$PWD/kubeconfig"
}

output "ansible_command" {
  description = "Configure the cluster after apply (inventory is generated by Terraform)."
  value       = "cd ../ansible && ansible-playbook site.yml"
}
